name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # 必要なNode.jsのバージョンを指定

    - name: Install dependencies
      run: npm install

    - name: Build site
      run: npm run ssg  # ssgスクリプトを実行

    - name: Deploy to deploy branch
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        # deploy ブランチをチェックアウト (存在しなければ作成)
        git fetch origin deploy || git checkout --orphan deploy
        git checkout deploy
        # 既存の内容を削除。ただし、distディレクトリを除外する
        shopt -s extglob  # bashの拡張グロブを有効にする
        rm -rf !(dist)  # distディレクトリ以外を削除
        cp -r dist/* .  # distディレクトリの内容をルートにコピー
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force origin deploy  # deployブランチに強制プッシュ

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}